# This file provides instructions for packaging.

`MooseX-MungeHas`
	perl_version_from m`MooseX::MungeHas`;
	version_from      m`MooseX::MungeHas`;
	readme_from       m`MooseX::MungeHas`;
	requires          p`Eval::TypeTiny 0.006`;
	test_requires     p`Test::More 0.96`;
	test_requires     p`Test::Requires 0.06`;
	test_requires     p`Test::Fatal`;
	test_requires     p`Types::Standard 0.006`;
	.

